### ISSUE TITLE
Support TimeZone

### ISSUE THREAD

**Issue by 1996fanrui** [cratesland/logforth#35]
As the follwing picture shown, I'm in UTC+8 TimeZone, but all time are shown by UTC+0 TimeZone, it includes:

- RollingFile name
- The time format of JsonLayout in RollingFile
- The time format of TextLayout in Stdout

And I'm willing to contribute it to support TimeZone. 

I could provide 2 solutions, and I'm not sure which one is better in the long term:

1. Don't support user set the TimeZone, and we use the default TimeZone of server
2. Using the default TimeZone of server by default, and user could set it (the default TimeZone will be overwrited)

<img width="1568" alt="img" src="https://github.com/user-attachments/assets/4a41a972-d56b-47ad-a553-17221bc94840">

**Comment by tisonkun** [comment]
You can try to implement option 2, while I may prefer to use UTC+0 as the default.

You can try to figure out how log4j or logback work on this aspect as extra input.

**Comment by 1996fanrui** [comment]
I checked the layout of logback[1] and log4j[2][3], both of them use the the default TimeZone of the host as the default TimeZone.

![img](https://github.com/user-attachments/assets/0ae51842-5cc5-44dd-9b83-b4b04eecb98b)


![img](https://github.com/user-attachments/assets/a5040701-7a88-4b7e-a94b-f73fadd0e2d4)


[1] https://logback.qos.ch/manual/layouts.html#date
[2] https://logging.apache.org/log4j/2.x/manual/layouts.html#html-layout
[3] https://docs.oracle.com/javase/6/docs/api/java/util/TimeZone.html#getDefault()

**Comment by tisonkun** [comment]
OK. Let's go in this direction for a try.
